### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Shreyanshp-3** [tehseen01/the-portfolio#1]
New using typescript,, but where is the raw data ??
export interface About {
  name: string;
  title: string;
  subTitle: string;
  description: string;
  quote: string;
  exp_year: string;
  address: string;
  some_total: string;
  phoneNumber: string;
  avatar: Avatar;
  alternateAvatars: any[];
}
M not getting the original source to update it.

**Comment by Shreyanshp-3** [comment]
![image](https://github.com/user-attachments/assets/90c1798a-0057-4fdd-a503-95c87b925b89)
Am i doing something wronge in searching or what not getting it?

**Comment by tehseen01** [comment]
I have added  a [dummy.json](https://github.com/tehseen01/the-portfolio/blob/main/src/dummy.json) file
